minutes/workload_orchestration_agent_meetings/2024.07.09-weekly.md

Adds WOA Meeting Minutes July 9

---

minutes/app_package_meetings/2024.07.10-weekly.md

Adds App Package FG meeting notes July 10

---

minutes/technical_sync_meetings/2024.07.11-weekly.md

Adds Technical Sync Meeting Notes July 11

---

minutes/workload_orchestration_agent_meetings/2024.07.16-weekly.md

Adds WOA Meeting Minutes July 16

---

minutes/app_package_meetings/2024.07.17-weekly.md

Adds App Package FG meeting notes July 17

---

minutes/app_package_meetings/2024.07.24-weekly.md

Adds App Package FG meeting notes July 24

---

minutes/workload_orchestration_agent_meetings/2024.07.23-weekly.md

Adds WOA Meeting Minutes July 23

---

minutes/technical_sync_meetings/2024.07.25-weekly.md

Adds Tech Sync Notes from July 25

---

minutes/workload_orchestration_agent_meetings/2024.07.30-weekly.md

Adds WOA Meeting Minutes July 30

---

minutes/app_package_meetings/2024.07.31-weekly.md

Adds App Package FG meeting notes July 31

---

minutes/technical_sync_meetings/2024.08.01-weekly.md

Adds Tech Sync Notes from Aug 1

---

minutes/app_package_meetings/2024.08.07-weekly.md

Adds app package call notes Aug. 7

---

minutes/workload_orchestration_agent_meetings/2024.08.06-weekly.md

adds WOA meeting notes from Aug. 6

---

minutes/joint_sc_twg_meetings/2024.08.08.md

Agenda for joint SC-TWG meeting Aug 8th 2024

Joint SC-TWG minutes 08AUG2024 - agenda

---

minutes/technical_sync_meetings/2024.08.09-weekly.md

Adds Tech Sync Notes Aug. 8

---

minutes/workload_orchestration_agent_meetings/2024.09.18-weekly.md

2024.09.18 Summary meeting minutes

---

minutes/app_package_meetings/2024.08.14_weekly.md

adds app package meeting notes from Aug. 14

---

minutes/technical_sync_meetings/2024.08.15-weekly.md

adds weekly technical sync notes Aug. 15

---

minutes/technical_sync_meetings/2024.08.22-weekly.md

adds tech sync minutes from Aug22

---

minutes/workload_orchestration_agent_meetings/2024.08.20-weekly.md

adds WOA meeting notes Aug. 20

---

minutes/workload_orchestration_agent_meetings/2024.08.13-weekly.md

adds meeting notes from 8.13 WOA call

---

minutes/app_package_meetings/2024.08.28-weekly.md

adds App Package meeting notes from Aug. 28

---

minutes/technical_sync_meetings/2024.08.29-weekly.md

adds technical sync meeting notes from Aug. 29

---

minutes/app_package_meetings/2024.09.04-weekly.md

adds meeting notes from Sept. 4 App Package meeting

---

minutes/workload_orchestration_agent_meetings/2024.09.03-weekly.md

Adds Meeting Notes for the Sept. 3 WOA Meeting

---

minutes/workload_orchestration_agent_meetings/2024.09.24-weekly.md

Adds Notes for the Sept. 24 WOA Meeting

---

minutes/app_package_meetings/2024.09.25-weekly.md

adds meeting notes from 25 Sept App meeting

---

minutes/app_package_meetings/2024.09.11-weekly.md

Adds notes from Sept. 11 App meeting

---

minutes/workload_orchestration_agent_meetings/2024.10.01-weekly.md

Adds Notes for the Oct 01 WOA Meeting

---

minutes/workload_orchestration_agent_meetings/2024.09.10-weekly.md

Adds notes from Sept. 10 WOA meeting

---

minutes/technical_sync_meetings/2024.09.12-weekly.md

Adds notes from Sept. 12 Tech Sync Meeting

---

minutes/app_package_meetings/2024.09.18-weekly.md

Adds meeting notes from Sept. 18 App Package meeting

---

minutes/technical_sync_meetings/2024.09.19-weekly.md

Adds notes from Sept. 19 Tech Sync Meeting

---

minutes/app_package_meetings/2024.10.02-weekly.md

This closes https://github.com/margo/technical-wg/issues/156

Adds meeting notes from 02 Oct App meeting

---

minutes/technical_sync_meetings/2024.10.10-weekly.md

Adds Notes for the 10-10 Technical Sync Meeting

---

minutes/technical_sync_meetings/2024.10.03-weekly.md

Adds Notes for the 10-03 Technical Sync Meeting

---

minutes/workload_orchestration_agent_meetings/2024.10.08-weekly.md

Adds Notes for the Oct 08 WOA Meeting

---

minutes/app_package_meetings/2024.10.23-weekly.md

Adds Notes for the Oct 23 App meeting

---

minutes/workload_orchestration_agent_meetings/2024.10.15-weekly.md

Adds Notes for the Oct 15 WOA Meeting

---

minutes/joint_sc_twg_meetings/2024.10.17.md

Notes added - 2024-10-17 Joint SC-TWG Bi-Weekly

---

minutes/app_package_meetings/2024.10.30-weekly.md

Adds Notes for the Oct 30 App meeting

---

minutes/app_package_meetings/2024.11.06-weekly.md

Adds notes from Nov. 06 app_package

---

minutes/technical_sync_meetings/2024.10.31-weekly.md

Notes added from weekly Tech-sync

---

minutes/technical_sync_meetings/2024.11.07-weekly.md

Adds notes from Nov. 07 Tech Sync Meeting

---

minutes/workload_orchestration_agent_meetings/2024.11.19-weekly.md

19-11 WOA Meeting notes

---

minutes/app_package_meetings/2024.11.13-weekly.md

Adds Notes for the 13 Nov App meeting

---

minutes/workload_orchestration_agent_meetings/2024.12.03-weekly.md

2024.12.03-weekly.md

---

minutes/app_package_meetings/2024.12.04-weekly.md

04 Dec - APP Package Meeting notes

2024.12.04-weekly.md

---

minutes/app_package_meetings/2024.12.11-weekly.md

2024.12.11-weekly.md

---

minutes/workload_orchestration_agent_meetings/2024.12.10-weekly.md

2024.12.10-weekly.md

---

minutes/technical_sync_meetings/2024.12.12-weekly.md

2024.12.12-weekly.md

---

minutes/workload_orchestration_agent_meetings/2025.01.07-weekly.md

2025.01.07 meeting notes.
Closes #222

2025.01.07-weekly.md

---

minutes/app_package_meetings/2025.01.08-weekly.md

2025.01.08-weekly.md

---

minutes/technical_sync_meetings/2025.01.09-weekly.md

2025.01.09 meeting notes
closes #223

2025.01.09-weekly.md

---

minutes/technical_sync_meetings/2025.01.16-weekly.md

16 Jan meeting notes
Closes #229

2025.01.16-Tech weekly

---

minutes/workload_orchestration_agent_meetings/2025.01.21-weekly.md

WOA 2025.01.21-weekly
Closes #233

2025.01.21-WOA weekly

---

minutes/app_package_meetings/2025.01.22-weekly.md

App-Package - 2025.01.22-weekly
#232

2025.01.22 - App-Package weekly

---

minutes/app_package_meetings/2025.02.05-weekly.md

App_package-2025.02.05-weekly meeting
Closes #241

App_package-2025.02.05-weekly.md

---

minutes/workload_orchestration_agent_meetings/2025.02.11-weekly.md

WOA - 2025.02.11-weekly

---

minutes/app_package_meetings/2025.02.12-weekly.md

App_Package- 2025.02.12-weekly
Closes #245

App_Package- 2025.02.12-weekly

---

minutes/workload_orchestration_agent_meetings/2025.02.18-weekly.md

WOA - 2025.02.18-meeting notes
closes #252

2025.02.18-weekly

---

minutes/workload_orchestration_agent_meetings/2025.02.25-weekly.md

WOA weekly meeting - 2025.02.25
Closes #257

WOA weekly meeting - 2025.02.25

---

minutes/app_package_meetings/2025.02.26-weekly.md

APP - 2025.02.26-weekly meeting notes
Closes #256

APP - 2025.02.26-weekly meeting notes

---

minutes/technical_sync_meetings/2025.02.13-weekly.md

TWG weekly sync - 2025.02.13
Closes #248

TWG weekly sync - 2025.02.13

---

minutes/app_package_meetings/2025.03.05-weekly.md

App-pk-2025.03.05-weekly
Closes #261

App-pk 2025.03.05 meeting notes

---

minutes/technical_sync_meetings/2025.03.06-weekly.md

Tech sync 2025.03.06-weekly meeting notes
Closes #263

Tech sync 2025.03.06-weekly meeting notes

---

minutes/workload_orchestration_agent_meetings/2025.03.11-weekly.md

WOA 2025.03.11-weekly meeting notes and Action Items Closes #267

WOA 2025.03.11-weekly meeting

---

minutes/app_package_meetings/2025.03.19-weekly.md

App_pk -2025.03.19-weekly
Closes #272

App_pk -2025.03.19-weekly

---

minutes/security_meetings/2025.03.24-weekly.md

2025.03.24-weekly Security meeting
closes #280

2025.03.24-weekly.md

---

minutes/technical_sync_meetings/2025.03.27-weekly.md

Tech-sync 2025.03.27-weekly
closes #282

Tech-sync 2025.03.27-weekly

---

minutes/workload_orchestration_agent_meetings/2025.04.03-weekly.md

WOA-weekly meeting
Closes #288

WOA 2025.04.01 weekly meeting

---

minutes/app_package_meetings/2025.04.02-weekly.md

App-Package 2025.04.02-weekly Meeting
Closes #287

App-Package 2025.04.02-weekly Meeting

---

minutes/technical_sync_meetings/2025.04.03-weekly.md

Tech Sync 2025.04.03-weekly.md

---

minutes/security_meetings/2025.04.07-weekly.md

Security 2025.04.07-weekly
Closes #294

Security 2025.04.07-weekly.md

---

minutes/workload_orchestration_agent_meetings/2025.04.08-weekly.md

WOA - 2025.04.08-weekly.md
Closes #296

WOA - 2025.04.08-weekly.md

---

minutes/app_package_meetings/2025-04-09-weekly.md

App-package-2025-04-09-weekly.md
Closes #295

App-package-2025-04-09-weekly.md
